FROM node:18

WORKDIR /app

COPY package*.json .

RUN npm ci

COPY svelte.config.js ./
COPY vite.config.ts ./
COPY tsconfig.json ./
COPY src/ ./src/
COPY static/ ./static/

RUN npm run build
RUN npm prune --production

CMD [ "npm", "run", "start" ]